### ISSUE TITLE
NPM package distributed as Typescript

### ISSUE THREAD

**Issue by V-Mann-Nick** [p2-inc/phasetwo-js#1]
Currently this package is distributed only as Typescript which makes it somewhat impossible to use:

https://www.npmjs.com/package/@p2-inc/js-sdk?activeTab=explore

I can see [build scripts](https://github.com/p2-inc/phasetwo-js/blob/8ad9115b4234ca10af6bc48aba7ee69a3b2559c5/package.json#L14-L17) but it seems that the `dist/` folder is not included in the package on npm.

**Comment by xgp** [comment]
Good catch. Try 0.0.3 and see if that works for you.

**Comment by V-Mann-Nick** [comment]
Yes. It works for me now. Thank you.
