### ISSUE TITLE
`addOrganizationInvitation` missing `redirectUri`

### ISSUE THREAD

**Issue by V-Mann-Nick** [p2-inc/phasetwo-js#2]
The [api docs](https://phasetwo.io/api/create-an-invitation-to-an-organization) talk about the field `redirectUri` for `POST /:realm/orgs/:orgId/invitations` but it's currently not supported by this package.

Perhaps you could rerun the Openapi codegen?

**Comment by xgp** [comment]
Done. In 0.0.4.

**Comment by V-Mann-Nick** [comment]
Thank you. These are really great extensions to Keyclaok.

**Comment by xgp** [comment]
Thanks. As you can tell, the SDK libs are pretty alpha. Please submit any issues you find with them, and we'll fix them right away.
