### ISSUE TITLE
Error when creating webhook

### ISSUE THREAD

**Issue by paulwer** [p2-inc/phasetwo-js#5]
I get a 400 error, when trying to create a new webhook with the sdk.
i guess this is because the property eventTypes gets casted to event_types, when sending the request. (confirmed: i just created an entry with postman while using the right parameter-name)

kcEventsClient.createWebhook({
  realm: auth.config.realmName,
  webhookRepresentation: {
    url: 'https://webhook.site/xxxxxxxxx',
    enabled: true,
    eventTypes: ['*'],
  },
})

{"error":"Unrecognized field \"event_types\" (class io.phasetwo.keycloak.representation.WebhookRepresentation), not marked as ignorable (9 known properties: \"secret\", \"enabled\", \"id\", \"url\", \"createdAt\", \"algorithm\", \"createdBy\", \"realm\", \"eventTypes\"])\n at [Source: (io.quarkus.vertx.http.runtime.VertxInputStream); line: 1, column: 98] (through reference chain: io.phasetwo.keycloak.representation.WebhookRepresentation[\"event_types\"])"}

**Comment by xgp** [comment]
Bug. Needs to be updated in [openapi.yml](https://github.com/p2-inc/phasetwo-docs/blob/master/openapi.yaml#L324)

**Comment by xgp** [comment]
Also, we might want to update these in the data objects with [`@JsonAlias`](https://www.javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/2.14.3/com/fasterxml/jackson/annotation/JsonAlias.html) as we make sure everything is standardized on snake case.

**Comment by paulwer** [comment]
any updates?

**Comment by xgp** [comment]
No. Feel free to PR

**Comment by paulwer** [comment]
i had in mind, that your https://github.com/p2-inc/phasetwo-docs/blob/master/openapi.yaml#L324 is updated automaticly?!
is this right? or can there be just a pr to this file from me?!

**Comment by paulwer** [comment]
in case this could "only" be edited in this file once i created a pr for this. Please update the client libraries accordingly afterwards :)

**Comment by paulwer** [comment]
@xgp thank you for accepting the PR. Please update the library accordingly.

Thank you <3

**Comment by xgp** [comment]
Lots of things going on, so probably no release until next week.

**Comment by paulwer** [comment]
friendly reminder :)

**Comment by paulwer** [comment]
again :)

**Comment by paulwer** [comment]
thank you very much <3
