### ISSUE TITLE
Missing Count User Orgs Endpoint / Method

### ISSUE THREAD

**Issue by paulwer** [p2-inc/phasetwo-js#6]
Is it possible to add this also?

**Comment by xgp** [comment]
Is this an existing endpoint, or something you want to add?

**Comment by paulwer** [comment]
i suggest adding this, so all get endpoint would have an additional count method?

EDIT: i just thought about it => if this endpoint returns all orgs and is not paginated, than a count would be obsolete and this can be closed. (if you like to add it, you can of cause)

**Comment by xgp** [comment]
Yes. This is why it wasn't added. Haven't encountered any use cases where a user was in so many orgs that this method needed to be paginated. And was secretly hoping that someone who had the case would PR it for me ;)
